#!/bin/bash
set -e

echo "REPLICATION_USER=$REPLICATION_USER"
echo "DB_USER=$DB_USER"

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<EOSQL

-- Replication user
CREATE ROLE $REPLICATION_USER WITH REPLICATION LOGIN PASSWORD '$REPLICATION_PASSWORD';

-- App user
CREATE ROLE $DB_USER WITH LOGIN PASSWORD '$DB_PASSWORD';

GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DB_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $DB_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO $DB_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO $DB_USER;

EOSQL